### PR TITLE
add CHAPTER option to makefile

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
This allows to compile only selected chapters via
```
make compile CHAPTER='<what-comes-after-"include|input{chapter|appendix/">'
```
note, that `/` has to be escaped as `\/`. Multiple chapters are separated by space. Depends on `vim` to be installed.
A makefile implementation of https://github.com/sisl/tufte_algorithms_book/issues/5#issuecomment-517837084.

### CODE REVIEW

**Comment by tawheeler** [comment]
Cool!

I ran `make compile CHAPTER='appendix'` and ended up with a bunch of stuff still included (title page, acknowledgements, etc.) Is it possible _only_ compile the chapter we want?

Also, could you update the README file with this documentation.

**Comment by johnnychen94** [comment]
Curiously asking, I'm wondering if there's specific reason not using `sed` here. (Not familiar with both `/` of `vim` and `sed` though.)

**Comment by BeastyBlacksmith** [comment]
it only comments stuff between `\mainmatter` and `\backmatter`. Could be changed to check between e.g. `\begin{document}` and `\end{document}`.
I had `sed` before, but found that it is hard to predict which of the many flavors is available on different machines. And `vim` seems to be more consistent in that regard.

**Comment by BeastyBlacksmith** [comment]
Changed the replace range. Give it a try and then I can update the README.

**Review by johnnychen94 — APPROVED** [review]

**Comment by tawheeler** [comment]
Great! Thanks.

**Pull request merged**
